backend:
  name: github
  repo: weslley343/weslley343.github.io
  branch: main

site_url: https://weslley343.github.io

media_folder: "assets/images/"
public_folder: "/assets/images/"

collections:
  - name: "blog"
    label: "Postagens"
    folder: "_posts" # Pasta onde o Markdown será criado
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Data de Publicação", name: "date", widget: "datetime"}
      - {label: "Resumo", name: "description", widget: "text"}
      - {label: "Corpo do Post", name: "body", widget: "markdown"}