backend:
  name: github
  repo: weslley343/weslley343.github.io
  branch: main

site_url: https://weslley343.github.io

media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"

    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Descrição", name: "description", widget: "text" }
      - { label: "Conteúdo", name: "body", widget: "markdown" }